DROP TABLE restaurants CASCADE;
DROP TABLE users CASCADE;
DROP TABLE reviews CASCADE;
CREATE TABLE restaurants (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT, password TEXT, op_status BOOLEAN);
CREATE TABLE reviews (id SERIAL PRIMARY KEY, restaurant_id INTEGER REFERENCES restaurants, user_id INTEGER REFERENCES users, rating INT, content TEXT, created_at TIMESTAMP);
INSERT INTO restaurants (name) VALUES ('Dilber');
INSERT INTO restaurants (name) VALUES ('King Kebab');
INSERT INTO restaurants (name) VALUES ('Hesburger');
INSERT INTO users (username, password, op_status) VALUES ('kalle123', 'pbkdf2:sha256:260000$R39gOQLbA9rEY3V8$6a62c79544143bb4a5afffcc2c0ac72bb9d65de1cf2d0f848d2f37727a68eef8', FALSE);