DROP TABLE IF EXISTS restaurants CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS group_members CASCADE;
CREATE TABLE restaurants (id SERIAL PRIMARY KEY, name TEXT);
CREATE TABLE users (id SERIAL PRIMARY KEY, username TEXT, password TEXT, op_status BOOLEAN);
CREATE TABLE reviews (id SERIAL PRIMARY KEY, restaurant_id INTEGER REFERENCES restaurants, user_id INTEGER REFERENCES users, username TEXT, rating INT, content TEXT, created_at TIMESTAMP, visible BOOLEAN);
CREATE TABLE likes (id SERIAL PRIMARY KEY, review_id INTEGER REFERENCES reviews, user_id INTEGER REFERENCES users);
CREATE TABLE groups (id SERIAL PRIMARY KEY, group_name TEXT, description TEXT);
CREATE TABLE group_members (id SERIAL PRIMARY KEY, group_id INTEGER REFERENCES groups, restaurant_id INTEGER REFERENCES restaurants);
INSERT INTO restaurants (name) VALUES ('Unicafe');
INSERT INTO restaurants (name) VALUES ('King Kebab');
INSERT INTO restaurants (name) VALUES ('Hesburger');
INSERT INTO users (username, password, op_status) VALUES ('admin', 'pbkdf2:sha256:260000$xUitMi5HcZSl5In7$c3e3b305a393913f0556d9bd1fe085ec30a5dbf80d7f176c04000e12ea69a48e', TRUE);